config/routes.rb
InternetMeatThermometerServer::Application.routes.draw do
  resources :thermometers

end

app/models/thermometer.rb
class Thermometer
  include Mongoid::Document
  include Mongoid::Timestamps::Updated
  field :deviceid, type: String
  field :temperature, type: Float
  field :_id, type: String, default: ->{deviceid}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/thermometers_controller.rb
class ThermometersController < ApplicationController
  skip_before_action :verify_authenticity_token
  before_action :set_thermometer, only: [:show, :edit, :update, :destroy ]
  before_action :set_cache_buster

  # GET /thermometers
  # GET /thermometers.json
  def index
    @thermometers = Thermometer.all
  end

  # GET /thermometers/1
  # GET /thermometers/1.json
  def show
  end

  # GET /thermometers/new
  def new
    @thermometer = Thermometer.new
  end

  # GET /thermometers/1/edit
  def edit
  end

  # POST /thermometers
  # POST /thermometers.json
  def create
    @thermometer = Thermometer.new(thermometer_params)

    respond_to do |format|
      if @thermometer.save
        format.html { redirect_to @thermometer, notice: 'Thermometer was successfully created.' }
        format.json { render action: 'show', status: :created, location: @thermometer }
      else
        format.html { render action: 'new' }
        format.json { render json: @thermometer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /thermometers/1
  # PATCH/PUT /thermometers/1.json
  def update
    respond_to do |format|
      if @thermometer.update(thermometer_params)
        format.html { redirect_to @thermometer, notice: 'Thermometer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @thermometer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /thermometers/1
  # DELETE /thermometers/1.json
  def destroy
    @thermometer.destroy
    respond_to do |format|
      format.html { redirect_to thermometers_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_thermometer
      @thermometer = Thermometer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def thermometer_params
      params.require(:thermometer).permit(:temperature, :deviceid)
    end

    def set_cache_buster
      response.headers["Cache-Control"] = "no-cache, no-store, max-age=0, must-revalidate"
      response.headers["Pragma"] = "no-cache"
      response.headers["Expires"] = "Fri, 01 Jan 1990 00:00:00 GMT"
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/thermometers_helper.rb
module ThermometersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>InternetMeatThermometerServer</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/thermometers/_form.html.erb
<%= form_for(@thermometer) do |f| %>
  <% if @thermometer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@thermometer.errors.count, "error") %> prohibited this thermometer from being saved:</h2>

      <ul>
      <% @thermometer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div class="field">
      <%= f.label :deviceid %><br>
      <%= f.text_field :deviceid %>
    </div>

    <div class="field">
    <%= f.label :temperature %><br>
    <%= f.text_field :temperature %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/thermometers/edit.html.erb
<h1>Editing thermometer</h1>

<%= render 'form' %>

<%= link_to 'Show', @thermometer %> |
<%= link_to 'Back', thermometers_path %>

app/views/thermometers/index.html.erb
<h1>Listing thermometers</h1>

<table>
  <thead>
    <tr>
      <th>Device ID</th>
      <th>Temperature</th>
      <th>Updated at</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @thermometers.each do |thermometer| %>
      <tr>
        <td><%= thermometer.deviceid %></td>
        <td><%= thermometer.temperature %></td>
        <td><%= thermometer.updated_at %></td>
        <td><%= link_to 'Show', thermometer %></td>
        <td><%= link_to 'Edit', edit_thermometer_path(thermometer) %></td>
        <td><%= link_to 'Destroy', thermometer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Thermometer', new_thermometer_path %>

app/views/thermometers/new.html.erb
<h1>New thermometer</h1>

<%= render 'form' %>

<%= link_to 'Back', thermometers_path %>

app/views/thermometers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Device ID:</strong>
  <%= @thermometer.deviceid %>
</p>

<p>
  <strong>Temperature:</strong>
  <%= @thermometer.temperature %>
</p>

<p>
  <strong>Updated at:</strong>
  <%= @thermometer.updated_at %>
</p>

<%= link_to 'Edit', edit_thermometer_path(@thermometer) %> |
<%= link_to 'Back', thermometers_path %>